name: pytorch-cuda-env
channels:
  - defaults
  - conda-forge
  - pytorch
  - comet_ml
dependencies:
  - python==3.8.5
  - numpy
  - pytorch
  - torchaudio
  - scikit-learn
  - pyyaml
  - pydub
  - pip
  - optuna
  - comet_ml
  - pandas
  - librosa
  - pip:
    - torchsummary
    - importlib-resources
