model:
  batch_size: 8
  epochs: 10
  learning_rate: 0.0001
  optimizer:
    type: "Adam"
  logging_batch_interval: 10
  epoch_patience: 10

discriminator:
  learning_rate: 0.001
  optimizer:
    type: "Adam"
