batch_size: 64
epochs: 10
logging_batch_interval: 10
epoch_patience: 10

model:
  learning_rate: 0.0001
  optimizer:
    type: "Adam"

discriminator:
  learning_rate: 0.0001
  optimizer:
    type: "Adam"
