name: Unittests and code check for 

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Use anaconda 
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: anaconda-client-env
          environment-file: unittest-environment.yml
          python-version: 3.8
          auto-activate-base: false
      # Runs flake command
      - name: Run flake
        run: |
          echo " ====== Running code styling check ======"
          conda install flake8
          flake8 . --count --exit-zero --max-complexity=10 --exclude test/* --max-line-length 127 --statistics

      # Runs a set of commands using the runners shell
      - name: Run unittests
        run: |
          echo " ====== Running unitests ======"
          python -m unittest discover --start-directory test/ -p "*_test.py"
